apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
- path: environment-patch-configmap.yml
- path: environment-patch-deployment.yml
- path: enviornment-patch-hpa.yml
- path: environment-patch-vpa.yml
- path: environment-patch-service.yml

# namePrefix: dev-
